import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet, TouchableOpacity } from 'react-native';
import { Card, Button, Input, Alert as AlertComponent, AlertModal, SecuritySelector, CustomList } from '../../components';
import { theme } from '../../constants';
import { api } from '../../services/api';
import { useAlertModal } from '../../hooks';
import type { Security } from '../../services/handlers/token.handler';

type ActionType = 'split' | 'symbol';

/**
 * Corporate Actions Screen
 * Execute stock splits and symbol changes
 */
export default function CorporateActions() {
    const [selectedSecurity, setSelectedSecurity] = useState<Security | null>(null);
    const [tokenMint, setTokenMint] = useState('');
    const [actionType, setActionType] = useState<ActionType>('split');

    // Stock Split State
    const [splitRatio, setSplitRatio] = useState('7');
    const [splitNewSymbol, setSplitNewSymbol] = useState('');
    const [splitNewName, setSplitNewName] = useState('');
    const [splitLoading, setSplitLoading] = useState(false);

    // Symbol Change State
    const [newSymbol, setNewSymbol] = useState('');
    const [newName, setNewName] = useState('');
    const [symbolLoading, setSymbolLoading] = useState(false);

    const { alertState, hideAlert, error, success, confirm, warning } = useAlertModal();

    // Auto-set token mint when security is selected
    useEffect(() => {
        if (selectedSecurity) {
            setTokenMint(selectedSecurity.mint_address);
        } else {
            setTokenMint('');
        }
    }, [selectedSecurity]);

    const handleSecuritySelected = (security: Security | null) => {
        setSelectedSecurity(security);
    };

    const executeStockSplit = async () => {
        if (!tokenMint || !splitRatio) {
            error('Error', 'Token mint and split ratio are required for stock split');
            return;
        }

        if (!selectedSecurity) {
            error('Error', 'Please select a security first');
            return;
        }

        const ratio = parseInt(splitRatio, 10);
        if (isNaN(ratio) || ratio <= 0) {
            error('Error', 'Split ratio must be a positive number');
            return;
        }

        // Auto-generate new symbol and name based on current security
        const autoGeneratedSymbol = selectedSecurity.symbol;
        const autoGeneratedName = `${selectedSecurity.name} (${ratio}-for-1 Split)`;

        confirm(
            'Confirm Stock Split',
            `This will create a new token and migrate all holders with a ${ratio}-for-1 split. This operation cannot be undone.\n\nNew Symbol: ${autoGeneratedSymbol}\nNew Name: ${autoGeneratedName}`,
            async () => {
                setSplitLoading(true);
                try {
                    const result = await api.executeStockSplit({
                        token_mint: tokenMint,
                        split_ratio: ratio,
                        new_symbol: autoGeneratedSymbol,
                        new_name: autoGeneratedName,
                    });

                    if (result.success) {
                        success(
                            'Success',
                            `Stock split executed successfully!\n\nNew Mint: ${result.new_mint}\nSignature: ${result.signature}`
                        );
                        // Clear form
                        setSplitRatio('7');
                        setSplitNewSymbol('');
                        setSplitNewName('');
                    } else {
                        error('Error', result.error || 'Failed to execute stock split');
                    }
                } catch (err) {
                    error('Error', (err as Error).message);
                } finally {
                    setSplitLoading(false);
                }
            }
        );
    };

    const changeSymbol = async () => {
        if (!tokenMint || !newSymbol || !newName) {
            error('Error', 'All fields are required for symbol change');
            return;
        }

        confirm(
            'Confirm Symbol Change',
            `Change token symbol to ${newSymbol}?`,
            async () => {
                setSymbolLoading(true);
                try {
                    const result = await api.changeSymbol({
                        token_mint: tokenMint,
                        new_symbol: newSymbol,
                        new_name: newName,
                    });

                    if (result.success) {
                        success('Success', 'Symbol changed successfully');
                        // Clear form
                        setNewSymbol('');
                        setNewName('');
                    } else {
                        error('Error', result.error || 'Failed to change symbol');
                    }
                } catch (err) {
                    error('Error', (err as Error).message);
                } finally {
                    setSymbolLoading(false);
                }
            }
        );
    };

    const renderRadioOption = (value: ActionType, label: string) => (
        <TouchableOpacity
            style={styles.radioOption}
            onPress={() => setActionType(value)}
        >
            <View style={styles.radioCircle}>
                {actionType === value && <View style={styles.radioInner} />}
            </View>
            <Text style={styles.radioLabel}>{label}</Text>
        </TouchableOpacity>
    );

    return (
        <>
            <AlertModal
                visible={alertState.visible}
                title={alertState.title}
                message={alertState.message}
                type={alertState.type}
                buttons={alertState.buttons}
                onClose={hideAlert}
            />
            <CustomList scrollViewProps={{ style: styles.container }}>
                <Card>
                    <Text style={styles.title}>Corporate Actions</Text>
                    <Text style={styles.description}>
                        Execute stock splits and symbol changes
                    </Text>
                </Card>

                <SecuritySelector
                    onSecuritySelected={handleSecuritySelected}
                    selectedSecurity={selectedSecurity}
                    emptyMessage="No securities found. Initialize a token first before executing corporate actions."
                    onError={error}
                    onWarning={warning}
                />

                {!selectedSecurity ? (
                    <Card>
                        <View style={styles.warningBox}>
                            <Text style={styles.warningText}>
                                ⚠️ Please select a security above first
                            </Text>
                        </View>
                    </Card>
                ) : (
                    <>
                        <Card>
                            <Text style={styles.sectionTitle}>Action Type</Text>
                            <View style={styles.radioContainer}>
                                {renderRadioOption('split', 'Stock Split')}
                                {renderRadioOption('symbol', 'Symbol Change')}
                            </View>
                        </Card>

                        {actionType === 'split' && (
                            <Card>
                                <Text style={styles.sectionTitle}>Stock Split Configuration</Text>
                                <AlertComponent
                                    variant="warning"
                                    message="This will create a new token and migrate all holders. Balances will be multiplied by the split ratio. The new token will keep the same symbol and the name will indicate the split."
                                />

                                <Input
                                    label="Split Ratio"
                                    value={splitRatio}
                                    onChangeText={setSplitRatio}
                                    placeholder="e.g., 7 for 7-for-1 split"
                                    keyboardType="numeric"
                                />

                                <Button
                                    title={`Execute ${splitRatio}-for-1 Stock Split`}
                                    variant="danger"
                                    onPress={executeStockSplit}
                                    loading={splitLoading}
                                />
                            </Card>
                        )}

                        {actionType === 'symbol' && (
                            <Card>
                                <Text style={styles.sectionTitle}>Symbol Change Configuration</Text>
                                <AlertComponent
                                    variant="info"
                                    message="This will update the token metadata. All balances remain unchanged."
                                />

                                <Input
                                    label="New Symbol"
                                    value={newSymbol}
                                    onChangeText={setNewSymbol}
                                    placeholder="e.g., ACMEX"
                                />

                                <Input
                                    label="New Name"
                                    value={newName}
                                    onChangeText={setNewName}
                                    placeholder="e.g., ACMEX Security Token"
                                />

                                <Button
                                    title="Update Token Metadata"
                                    variant="primary"
                                    onPress={changeSymbol}
                                    loading={symbolLoading}
                                />
                            </Card>
                        )}
                    </>
                )}
            </CustomList>
        </>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.colors.background.primary,
    },
    title: {
        fontSize: theme.typography.fontSize['2xl'],
        fontWeight: theme.typography.fontWeight.bold,
        color: theme.colors.text.primary,
        marginBottom: theme.spacing.xs,
    },
    description: {
        fontSize: theme.typography.fontSize.base,
        color: theme.colors.text.secondary,
    },
    sectionTitle: {
        fontSize: theme.typography.fontSize.lg,
        fontWeight: theme.typography.fontWeight.semibold,
        color: theme.colors.text.primary,
        marginBottom: theme.spacing.md,
    },
    warningBox: {
        padding: theme.spacing.md,
        backgroundColor: '#FFF3CD',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#FFC107',
    },
    warningText: {
        fontSize: theme.typography.fontSize.base,
        color: '#856404',
        textAlign: 'center',
    },
    radioContainer: {
        flexDirection: 'column',
        gap: theme.spacing.sm,
    },
    radioOption: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: theme.spacing.sm,
    },
    radioCircle: {
        width: 24,
        height: 24,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: theme.colors.primary.default,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: theme.spacing.sm,
    },
    radioInner: {
        width: 12,
        height: 12,
        borderRadius: 6,
        backgroundColor: theme.colors.primary.default,
    },
    radioLabel: {
        fontSize: theme.typography.fontSize.base,
        color: theme.colors.text.primary,
    },
});

